n = input("Digite algo: ")
print("O tipo primitivo desse valor é: ",type(n))
print("So tem espaços? ",n.isspace())
print("É um numero? ",n.isnumeric())
print("É alfabetico? ",n.isalpha())
print("É alfanumerico? ",n.isalnum())
print("Está em maiusculas? ",n.isupper())
print("Está em minusculas? ",n.islower())
print("Está capitalizada? ",n.istitle())